services:
  - type: web
    name: smm-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Smmtgg.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
